### ISSUE TITLE
Finalize syllabus

### ISSUE THREAD

**Issue by baileyfosdick** [geanders/csu_msmb#1]
- Add syllabus to github
- Add calendar

**Comment by geanders** [comment]
@baileyfosdick  and @lyonsm7: Make sure you add your names to the "Author" markup at the top of the blog post text so you'll show up as authors.

**Comment by geanders** [comment]
@baileyfosdick and @lyonsm7: I haven't connected the Overleaf project and the website's GitHub repository yet, so the website's version of the syllabus won't automatically update. I'll be sure to move in the latest version of the syllabus before class today, though, so we'll have the Overleaf version on the website.

**Comment by baileyfosdick** [comment]
I updated the syllabus and added deadlines I think is reasonable.  Once you both look it over, feel free to close this issue if you feel it is complete.

**Comment by geanders** [comment]
I just took a look and I think it looks really great. @lyonsm7, once you get a chance to look at it and give your okay, I'll put this updated version on the website and close this issue.
