### ISSUE TITLE
Write blog post on how to create an exercise blog post

### ISSUE THREAD

**Issue by geanders** [geanders/csu_msmb#32]

**Comment by geanders** [comment]
@baileyfosdick and @lyonsm7 : I've add the blog post on creating an exercise blog post. Please make any edits you'd like to that---I tried to make sure it was consistent with what we'd said in the syllabus.

**Comment by baileyfosdick** [comment]
@geanders Looks fantastic!  The solution for the exercise for Chpt 1 also looks great.

**Comment by geanders** [comment]
Awesome! I think we're all set with example and how-to posts, then.
