### ISSUE TITLE
Finish MSMB review

### ISSUE THREAD

**Issue by baileyfosdick** [geanders/csu_msmb#63]
@geanders  I have added text for all my portions and commented out the bullets to start to see how it flows.  We could add subsection headings if we wanted, though probably unnecessary.  I think now we just need to tighten it up and smooth it out.  I have time this afternoon or tomorrow morning to get back to it.

**Comment by geanders** [comment]
I just took another pass. I reordered the paragraphs a bit and worked in the "community" on GitHub idea within a paragraph on the online accessibility. I also cleaned up the wording in the paragraphs that I drafted, so hopefully the style flows a little better throughout. I think this is probably ready to share with students now?

**Comment by baileyfosdick** [comment]
Great.  I will take a pass.  What do you think would be the best way to share it? I guess email a pdf to everyone? I initially thought a blog post but since the website is public that might be odd.  Also, what did you think of the last few paragraphs I wrote related to audience?  Any suggestions or revisions?

**Comment by geanders** [comment]
Yes, I think a pdf would be best. I like the last couple of paragraphs about the audience a lot. I think this a fair assessment, particularly since the book specifically advertises itself as being for biologists / scientists working in biological sciences, which it does on the back cover and in the introduction.
________________________________

**Comment by baileyfosdick** [comment]
Improved formatting for submission.  Do you want to send it out with the class details for tomorrow?

**Comment by baileyfosdick** [comment]
I did a full read also and think it is really good!

**Comment by geanders** [comment]
Great. Yes, I'll send it out!
________________________________
