### ISSUE TITLE
Make schedule for student vocab and exercise assignments

### ISSUE THREAD

**Issue by geanders** [geanders/csu_msmb#7]

**Comment by geanders** [comment]
We now have a "Schedule" section in our webpage: 

https://kind-neumann-789611.netlify.com/

There is room in each entry for us to put the exercise(s) for the week and which students are assigned to the vocabulary list and the "official" version of the exercise.

**Comment by geanders** [comment]
It works out perfectly if we do two weeks on Chapter 2 (Statistical Modeling) and one week for every other chapter except Chapter 3 (the plotting one). 

Chapter | Date
------- | ------
1 | Feb. 6
2 | Feb. 13--20
4 | Feb. 27
5 | March 5
6 | March 12
7 | March 26
8 | April 2
9 | April 9 
10 | April 16
11 | April 23
12 | April 30
13 | May 7

**Comment by geanders** [comment]
@lyonsm7 had the suggestion that, if we had the chance to do two-week sessions for other chapters, these would be the ones: 

10 Networks and trees, 5 Clustering, 7 Multivariate analysis

So we might need to decide if we want to go broader and cover all chapters or deeper on a few and take some out. 

I'd probably vote on trying to get to all the chapters (except Ch. 3) if we can.

**Comment by geanders** [comment]
Here were Mike's suggestions for the exercises for each chapter: 

Exercises:
1.5, 2.3, 3.3, 4.1, 5.5, 6.7, 7.1, 8.2, 9.2, 10.1,
10.4, 11.5, 12.4, 13.1

**Comment by geanders** [comment]
We will have more weeks than students, I think, so right now I've put down on the syllabus that we (Faculty) will also do the vocabulary list for Chapter 2. This should give the students an idea of what we're looking for before we start having them do it. 

I'm thinking one of us might also want to do the first "official" exercise post, again so they'll get an idea of what we're looking for and so that we don't have a student who has to do an exercise so early in the semester. What do you think?

**Comment by baileyfosdick** [comment]
I agree let's try to get through the entire book.  Students can always go back and dig deeper in chapters that specifically interest them.

I updated the schedule and broke chapter 2 into 2.1-2.7 and 2.8-2.12.  This seemed like a natural split to me but see what you think.  

Since we will have more weeks than students, I wrote in the syllabus that students will have to do vocab "once or twice" and an exercise solution "once or twice".  If we have 6 students, they might each do 2 vocabs and 2 exercise solutions.  After class today we should know exactly how many students we have and can make the final call.  I worry if we say one vocab and one exercise, that leaves a lot for us to do!

**Comment by geanders** [comment]
Sounds great to me!

**Comment by geanders** [comment]
@baileyfosdick and @lyonsm7 : I've drafted the student assignments for the next few weeks on our Overleaf syllabus document. Take a look and see if those look good to you. If so, I'll add them into the website, too (and update the syllabus there).

**Comment by baileyfosdick** [comment]
@geanders Is there any reason not to fill the rest of the assignments in for the semester?  We have 11 students and 12 openings remaining so those that did exercises can then do vocab and visa versa.  That will leave one spot remaining, which we could fill in.  I am happy to throw some names in.

**Comment by geanders** [comment]
That would be great! Amy Fox ended up doing a lot more of the vocabulary than most other students will, because we kept changing the assignment for her, so maybe let's put her for a lighter exercise if we can to compensate. I think the only other restriction was the one request for assignments later in the semester. 

Once we draft the schedule, we should doublecheck with the folks who are auditing or sitting in that they can commit to the assignments we've put in for them and adapt if needed.
