### ISSUE TITLE
Pick exercise(s) for each chapter

### ISSUE THREAD

**Issue by geanders** [geanders/csu_msmb#8]

**Comment by geanders** [comment]
Here were @lyonsm7's suggestions for the exercises for each chapter:

Exercises:
1.5, 2.3, 3.3, 4.1, 5.5, 6.7, 7.1, 8.2, 9.2, 10.1,
10.4, 11.5, 12.4, 13.1

**Comment by geanders** [comment]
I'd add the following to consider: 

6.4, 7.2, 8.1, 10.8, 11.1 and 11.3 (together as one exercise), 12.1 or 12.2, 13.2

**Comment by baileyfosdick** [comment]
My original suggestions:

1.5/1.8, 2.3, 3.4 (not necessary), 4.1/4.3, 5.1/5.3 (not a big stat preference), (6.2,6.3,6.6) - discussion

**Comment by geanders** [comment]
Great! I think we have a nice set of possibilities. I suggest that we pick and post each about a week or so before we get to that chapter, so we can play it by ear a bit in terms of which types of exercises seem to work out best for in-class work for the students.

**Comment by geanders** [comment]
@baileyfosdick : for chapter 8, I think exercise 8.1 would work better than the other option. What do you think? Once we pick, I'll add it to the schedule.

**Comment by baileyfosdick** [comment]
8.1 sounds good to me.
